name: Remote Desktop

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

on: 
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating system'
        type: choice
        required: true
        default: 'windows-latest'
        options:
          - windows-latest
          - ubuntu-latest
          - macos-latest
      password:
        description: 'Password'
        type: string
        required: true

jobs:
  remote:
    runs-on: ${{ inputs.os }}
    timeout-minutes: 360
    env:
      PORT: 8080
      METRICS_PORT: 1337
    permissions:
      statuses: write

    steps:
      - name: Copy repository into PC
        uses: actions/checkout@v7
      
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Linux setup
        if: runner.os == 'Linux'
        run: |
          # Use docker one day

          # Cloudflared stuff
          sudo mkdir -p --mode=0755 /usr/share/keyrings
          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflared.list

          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            xfce4 \
            dbus-x11 \
            xvfb \
            libxtst-dev \
            cloudflared

          read -r DISPLAY_NUMBER < <(exec Xvfb -displayfd 1 -screen 0 1920x1080x24 +extension XTEST -nolisten tcp)

          export DISPLAY=":$DISPLAY_NUMBER"
          echo "DISPLAY=$DISPLAY" >> "$GITHUB_ENV"
          echo "ELECTRON_DISABLE_SANDBOX=1" >> $GITHUB_ENV

          eval "$(dbus-launch --sh-syntax)"
          echo "DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS" >> "$GITHUB_ENV"
          echo "DBUS_SESSION_BUS_PID=$DBUS_SESSION_BUS_PID" >> "$GITHUB_ENV"

          startxfce4 &

      - name: MacOS setup
        if: runner.os == 'macOS'
        run: |
          brew install cloudflared

      - name: Windows setup
        if: runner.os == 'Windows'
        run: |
          winget install -e --id=Cloudflare.cloudflared --accept-package-agreements --accept-source-agreements --disable-interactivity

      - name: Start server
        background: true
        run: |
          npx remote-desktop --port="${PORT}" --password=${{ inputs.password }}

      - name: Install cloudflared
        id: tunnel
        run: |
          cloudflared tunnel --metrics "localhost:${METRICS_PORT}" --url "http://localhost:${PORT}" &

          until cloudflared tunnel --metrics "localhost:${METRICS_PORT}" ready; do
            sleep 0.5
          done

          TUNNEL_URL=$(curl -s http://localhost:${METRICS_PORT}/quicktunnel | jq -r '.hostname')
          touch "${TUNNEL_URL}"
          echo "url=${TUNNEL_URL}" >> "${GITHUB_OUTPUT}"

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.tunnel.outputs.url }}
          archive: false